os: linux
dist: bionic

language: python
python:
  - "3.6"
  - "3.7"

before_install:
 - sudo apt-get -y -qq update
 - sudo apt-get -y -qq install ffmpeg

script:
 - python3 setup.py test

notifications:
  email:
    - dev-celerity+travis@ubicast.eu
